market/market/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from app_login.views import (UserPasswordResetCompleteView,
                             UserPasswordResetConfirmView,
                             UserPasswordResetDoneView,
                             UserResetPasswordView)

urlpatterns = [
                  path('', include('market_app.urls')),
                  path('i18n', include('django.conf.urls.i18n')),
                  path('admin/', admin.site.urls),
                  path('settings/', include('app_settings.urls')),
                  path('comparison/', include('compare_app.urls')),
                  path('login/', include('app_login.urls')),
                  path('password-reset/', UserResetPasswordView.as_view(), name='password_reset'),
                  path('password-reset/done/', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
                  path('reset/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(),
                       name='password_reset_confirm'),
                  path('reset/done/', UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
                  path('cart/', include('app_cart.urls')),
                  path('account/', include('app_profile.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market/market_app/forms.py
from django import forms


class ProductReviewForm(forms.Form):
    description = forms.CharField(max_length=2000)
    # Эту часть ввести после добавления загрузки фото с отзывами
    # images = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=False)

market/templates/about.html
{% extends "base/base.html" %}
{% load static %}

{% block content %}
    <div class="Section Section_column Section_columnLeft Section_columnWide">
      <div class="wrap">
        <div class="Section-column">

          {% include "include/shipping_and_returns.html" %}

          {% include "include/follow_us.html" %}

        </div>
        <div class="Section-content">
          <article class="Article">
            <div class="Article-section">
              <div class="row row_verticalCenter row_maxHalf">
                <div class="row-block">
                  <h2>Why Choose Megano?
                  </h2>
                  <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit doli. Aenean commodo ligula eget dolor. Aenean massa. Cumtipsu sociis natoque penatibus et magnis dis parturient montesti, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eutu, pretiumem.
                  </p>
                  <p>Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justotuio, rhoncus ut loret, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus element semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae  ligula eget dolor. Aenean massa. Cumtipsu sociis natoque pena tibusetm t semper ni.
                  </p>
                  <div><a class="btn btn_primary" href="#">Get Started</a>
                  </div>
                </div>
                <div class="row-block">
                  <div class="pict"><img src="{% static "assets/img/content/home/slider.png" %}" alt="slider.png"/>
                  </div>
                </div>
              </div>
            </div>
            <div class="Article-section">
              <div class="row row_verticalCenter row_maxHalf">
                <div class="row-block">
                  <div class="pict"><img src="{% static "assets/img/content/home/bigGoods.png" %}" alt="bigGoods.png"/>
                  </div>
                </div>
                <div class="row-block">
                  <h2>Megano Store Hystory
                  </h2>
                  <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit doli. Aenean commodo ligula eget dolor. Aenean massa. Cumtipsu sociis natoque penatibus et magnis dis parturient montesti, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eutu, pretiumem.
                  </p>
                  <ul>
                    <li>Lorem ipsum dolor sit amet, consectetuer
                    </li>
                    <li>adipiscing elit doli. Aenean commodo ligula
                    </li>
                    <li>eget dolor. Aenean massa. Cumtipsu sociis
                    </li>
                    <li>natoque penatibus et magnis dis parturient
                    </li>
                    <li>montesti, nascetur ridiculus mus. Donec
                    </li>
                    <li>quam felis, ultricies nec, pellentesque eutu
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </article>
        </div>
      </div>
    </div>

{% endblock content %}

market/templates/account.html
{% extends "base/profile_base.html" %}
{% load static %}
{% load i18n %}

{% block profile_content %}

    <div class="Account">
        <div class="Account-group">
            <div class="Account-column">
                <div class="Account-avatar"><img src="../media/{{ profile.avatar.avatar }}" alt="card.jpg"/>
                </div>
            </div>
            <div class="Account-column">
                <div class="Account-name">{{ profile.full_name }}
                </div><a class="Account-editLink" href="{% url 'profile' %}">{% trans "Редактировать профиль" %}</a>
            </div>
        </div>
        <div class="Account-group">
            <div class="Account-column Account-column_full">
                {% if oneorder %}
                    {% for order in oneorder %}
                        <div class="Order Order_anons">
                            <div class="Order-personal">
                                <div class="row">
                                    <div class="row-block">
                                        <a class="Order-title" href="../order/detail/{{ order.order_id }}/">
                                            {% trans "Заказ" %}&#32;<span class="Order-numberOrder">№{{ order.order_id }}
                                            </span>&#32;{% trans "от" %}&#32;<span class="Order-dateOrder">{{ order.added_date }}</span></a>
                                        <div class="Account-editLink">
                                            <a href="{% url 'historyorder' %}">{% trans "История заказов" %}</a>
                                        </div>
                                    </div>
                                    <div class="row-block">
                                        <div class="Order-info Order-info_delivery">
                                            <div class="Order-infoType">{% trans "Тип доставки:" %}
                                            </div>
                                            <div class="Order-infoContent">{{ order.delivery }}
                                            </div>
                                        </div>
                                        <div class="Order-info Order-info_pay">
                                            <div class="Order-infoType">{% trans "Оплата:" %}
                                            </div>
                                            <div class="Order-infoContent">{{ order.pay }}
                                            </div>
                                        </div>
                                        <div class="Order-info">
                                            <div class="Order-infoType">{% trans "Общая стоимость:" %}
                                            </div>
                                            <div class="Order-infoContent">{{ order.total_price }} ₽
                                            </div>
                                        </div>
                                        <div class="Order-info Order-info_status">
                                            <div class="Order-infoType">{% trans "Статус:" %}
                                            </div>
                                            <div class="Order-infoContent">{{ order.payment_status }}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <span>{% trans "Активных заказов пока нет" %}</span>
                {% endif %}
            </div>
        </div>
        <div class="Account-group">
            <div class="Account-column Account-column_full">
                <header class="Section-header">
                    <h2 class="Section-title">{% trans "История просмотров" %}
                    </h2>
                </header>

                {# История просмотров #}

                {% if history_view_list %}
                    <div class="Cards Cards_account">
                        {# На этой странице выводим не более 3 заказов #}
                        {% for card in history_view_list|slice:":3" %}

                            <div class="Card{% cycle ' ' ' hide_700' ' hide_md' %}">
                                {% include 'include/card.html' %}
                            </div>

                        {% endfor %}

                    </div>
                    <div class="Account-editLink Account-editLink_view">
                        <a href="{% url 'historyview' %}">{% trans "Перейти на полный список" %}</a>
                    </div>

                {% else %}
                    <span>{% trans "Вы пока не просмотрели ни один товар" %}</span>
                {% endif %}

            </div>
        </div>
    </div>

{% endblock profile_content %}

market/templates/catalog.html
{% extends "base/base.html" %}
{% load static %}
{% load i18n %}

{% block content %}

    <div class="Section Section_column Section_columnLeft">
      <div class="wrap">
        <div class="Section-column">
          <div class="Section-columnSection">
            <header class="Section-header">
              <strong class="Section-title">{% trans 'Фильтр' %}
              </strong>
            </header>
            <div class="Section-columnContent">
              <form class="form" action="{% url 'catalog' %}" method="get">
                <div class="form-group">
                  <div class="range Section-columnRange">
                    <input class="range-line" id="price" name="price" type="text" data-type="double" data-min="7" data-max="1000000" data-from="7" data-to="1000000"/>
                    <div class="range-price">{% trans 'Цена' %}:&#32;
                      <div class="rangePrice">
                      </div>
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <input class="form-input form-input_full" id="title" name="title" type="text" placeholder="{% trans 'Название' %}"/>
                </div>
                <div class="form-group">
                  <select class="form-select">
                    <option value="seller" selected="selected" disabled="disabled">{% trans 'Продавец' %}
                    </option>
                    <option value="kkk">Kkkk
                    </option>
                    <option value="sdfsdf">sdfsdf
                    </option>
                  </select>
                </div>
                <div class="form-group">
                  <label class="toggle">
                    <input name="stock" type="checkbox"/><span class="toggle-box"></span><span class="toggle-text">{% trans 'Только товары в наличии' %}</span>
                  </label>
                </div>
                <div class="form-group">
                  <label class="toggle">
                    <input type="checkbox"/><span class="toggle-box"></span><span class="toggle-text">{% trans 'С бесплатной доставкой' %}</span>
                  </label>
                </div>
                <div class="form-group">
                  <div class="buttons"><input class="btn btn_square btn_dark btn_narrow" type="submit" value="{% trans 'Фильтр' %}">
                  </div>
                </div>
              </form>
            </div>
          </div>
          <div class="Section-columnSection">
            <header class="Section-header">
              <strong class="Section-title">{% trans 'Популярные теги' %}
              </strong>
            </header>
            <div class="Section-columnContent">
              <div class="buttons">
                  <a class="btn btn_default btn_sm" href="#">{% trans 'Видео' %}</a>
                  <a class="btn btn_default btn_sm" href="#">{% trans 'Разработка' %}</a>
                  <a class="btn btn_default btn_sm" href="#">{% trans 'Игры' %}</a>
                  <a class="btn btn_default btn_sm" href="#">{% trans 'Асус' %}</a>
                  <a class="btn btn_default btn_sm" href="#">{% trans 'Разработка' %}</a>
                  <a class="btn btn_default btn_sm" href="#">{% trans 'Видео' %}</a>
              </div>
            </div>
          </div>
        </div>
        <div class="Section-content">
          <div class="Sort">
            <div class="Sort-title">{% trans 'Сортировать по:' %}
            </div>
            <div class="Sort-variants">
                {% if not sort_by %}
                    <a class="Sort-sortBy" href="?{{ add_url }}&sort_by=rating">{% trans 'Популярности' %}</a>
                    <a class="Sort-sortBy Sort-sortBy_inc" href="?{{ add_url }}&sort_by=price">{% trans 'Цене' %}</a>
                    <a class="Sort-sortBy" href="?{{ add_url }}&sort_by=count_reviews">{% trans 'Отзывам' %}</a>
                    <a class="Sort-sortBy" href="?{{ add_url }}&sort_by=year">{% trans 'Новизне' %}</a>
                {% elif sort_by == "price" %}
                    <a class="Sort-sortBy" href="?{{ add_url }}&sort_by=rating">{% trans 'Популярности' %}</a>
                    <a class="Sort-sortBy Sort-sortBy_dec" href="?{{ add_url }}&sort_by=-price">{% trans 'Цене' %}</a>
                    <a class="Sort-sortBy" href="?{{ add_url }}&sort_by=count_reviews">{% trans 'Отзывам' %}</a>
                    <a class="Sort-sortBy" href="?{{ add_url }}&sort_by=year">{% trans 'Новизне' %}</a>
                {% elif sort_by == "-price" %}
                    <a class="Sort-sortBy" href="?{{ add_url }}&sort_by=rating">{% trans 'Популярности' %}</a>
                    <a class="Sort-sortBy Sort-sortBy_inc" href="?{{ add_url }}&sort_by=price">{% trans 'Цене' %}</a>
                    <a class="Sort-sortBy" href="?{{ add_url }}&sort_by=count_reviews">{% trans 'Отзывам' %}</a>
                    <a class="Sort-sortBy" href="?{{ add_url }}&sort_by=year">{% trans 'Новизне' %}</a>
                {% elif sort_by == "count_reviews" %}
                    <a class="Sort-sortBy" href="?{{ add_url }}&sort_by=rating">{% trans 'Популярности' %}</a>
                    <a class="Sort-sortBy" href="?{{ add_url }}&sort_by=-price">{% trans 'Цене' %}</a>
                    <a class="Sort-sortBy Sort-sortBy_dec" href="?{{ add_url }}&sort_by=-count_reviews">{% trans 'Отзывам' %}</a>
                    <a class="Sort-sortBy" href="?{{ add_url }}&sort_by=year">{% trans 'Новизне' %}</a>
                {% elif sort_by == "-count_reviews" %}
                    <a class="Sort-sortBy" href="?{{ add_url }}&sort_by=rating">{% trans 'Популярности' %}</a>
                    <a class="Sort-sortBy" href="?{{ add_url }}&sort_by=price">{% trans 'Цене' %}</a>
                    <a class="Sort-sortBy Sort-sortBy_inc" href="?{{ add_url }}&sort_by=count_reviews">{% trans 'Отзывам' %}</a>
                    <a class="Sort-sortBy" href="?{{ add_url }}&sort_by=year">{% trans 'Новизне' %}</a>
                {% elif sort_by == "year" %}
                    <a class="Sort-sortBy" href="?{{ add_url }}&sort_by=rating">{% trans 'Популярности' %}</a>
                    <a class="Sort-sortBy" href="?{{ add_url }}&sort_by=-price">{% trans 'Цене' %}</a>
                    <a class="Sort-sortBy" href="?{{ add_url }}&sort_by=-count_reviews">{% trans 'Отзывам' %}</a>
                    <a class="Sort-sortBy Sort-sortBy_dec" href="?{{ add_url }}&sort_by=-year">{% trans 'Новизне' %}</a>
                {% elif sort_by == "-year" %}
                    <a class="Sort-sortBy" href="?{{ add_url }}&sort_by=rating">{% trans 'Популярности' %}</a>
                    <a class="Sort-sortBy" href="?{{ add_url }}&sort_by=price">{% trans 'Цене' %}</a>
                    <a class="Sort-sortBy" href="?{{ add_url }}&sort_by=count_reviews">{% trans 'Отзывам' %}</a>
                    <a class="Sort-sortBy Sort-sortBy_inc" href="?{{ add_url }}&sort_by=year">{% trans 'Новизне' %}</a>
                {% elif sort_by == "rating" %}
                    <a class="Sort-sortBy Sort-sortBy_dec" href="?{{ add_url }}&sort_by=-rating">{% trans 'Популярности' %}</a>
                    <a class="Sort-sortBy" href="?{{ add_url }}&sort_by=-price">{% trans 'Цене' %}</a>
                    <a class="Sort-sortBy" href="?{{ add_url }}&sort_by=-count_reviews">{% trans 'Отзывам' %}</a>
                    <a class="Sort-sortBy" href="?{{ add_url }}&sort_by=-year">{% trans 'Новизне' %}</a>
                {% elif sort_by == "-rating" %}
                    <a class="Sort-sortBy Sort-sortBy_inc" href="?{{ add_url }}&sort_by=rating">{% trans 'Популярности' %}</a>
                    <a class="Sort-sortBy" href="?{{ add_url }}&sort_by=price">{% trans 'Цене' %}</a>
                    <a class="Sort-sortBy" href="?{{ add_url }}&sort_by=count_reviews">{% trans 'Отзывам' %}</a>
                    <a class="Sort-sortBy" href="?{{ add_url }}&sort_by=year">{% trans 'Новизне' %}</a>
                {% endif %}
            </div>
          </div>
          <div class="Cards">
            {% for card in cards %}
              <div class="Card{% cycle ' ' ' ' ' ' ' ' ' hide_md' ' hide_md' ' hide_md hide_1450' ' hide_md hide_1450' %}">
                 {% include 'include/card.html' %}
              </div>
            {% endfor %}
          </div>
          <div class="Pagination">
            <div class="Pagination-ins">
              {% if cards.has_previous %}
              <a class="Pagination-element Pagination-element_prev" href="?page={{ cards.previous_page_number }}#reviews">
                <img style="margin: 0;" src="{% static "assets/img/icons/prevPagination.svg" %}" alt="prevPagination.svg"/>
              </a>
              {% endif %}
              {% for page in cards.paginator.page_range %}
                {% if cards.number == page %}
                <a class="Pagination-element Pagination-element_current" href="?page={{ page }}#reviews">
                  <span class="Pagination-text">{{ page }}
                  </span>
                </a>
                {% elif page >= cards.number|add:-2 and page <= cards.number|add:2 %}
                <a class="Pagination-element" href="?page={{ page }}#reviews">
                  <span class="Pagination-text">{{ page }}
                  </span>
                </a>
              {% endif %}
              {% endfor %}
              {% if cards.has_next %}
              <a class="Pagination-element Pagination-element_prev" href="?page={{ cards.next_page_number }}#reviews">
                <img style="margin: 0;" src="{% static "assets/img/icons/nextPagination.svg" %}" alt="nextPagination.svg"/>
              </a>
              {% endif %}
            </div>
          </div>
      </div>
    </div>

{% endblock content %}

market/templates/product.html
{% extends "base/base.html" %}
{% load static %}
{% load i18n %}

{% block content %}

    <div class="Section">
      <div class="wrap">
        <div class="Product">
          <div class="ProductCard">
            <div class="ProductCard-look">
              <div class="ProductCard-photo">
                  <img src="{{ MEDIA_ROOT }}{{ images.first.image.url }}" alt={{ images.first.image_alt }}/>
              </div>
              <div class="ProductCard-picts">
                {% for image in images %}
                  <a class="ProductCard-pict ProductCard-pict_ACTIVE" href="{{ MEDIA_ROOT }}{{ image.image.url }}">
                    <img src="{{ MEDIA_ROOT }}{{ image.image.url }}" alt={{ image.image_alt }}/>
                  </a>
                {% endfor %}
              </div>
            </div>
            <div class="ProductCard-desc">
              <div class="ProductCard-header">
                <h2 class="ProductCard-title">{{ product.name }}
                </h2>
                <div class="ProductCard-info">
                  <div class="ProductCard-cost">
                    <div class="ProductCard-price">₽ {{ min_price }}
                    </div>
                  </div>
                  <div class="ProductCard-compare">
                      <a class="btn btn_default" href="{% url 'add-good-for-compare' product.id %}">
                          <img class="btn-icon" src="{% static "assets/img/icons/card/change.svg" %}" alt="change.svg"/>
                      </a>
                  </div>
                </div>
              </div>
              <div class="ProductCard-text">
                <ul>
                  <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, eiusmod
                  </li>
                  <li>tempor incididunt ut labore et dolore magna aliqua. Lorem
                  </li>
                  <li>ipsum dolor sit ameabore et dolore magna aliqua. Lorem ipsum
                  </li>
                </ul>
              </div>
            </div>
          </div>
          <div class="Tabs Tabs_default">
            <div class="Tabs-links">
                <a class="Tabs-link_ACTIVE Tabs-link" href="#description">
                    <span>{% trans "Описание" %}</span>
                </a>
                <a class="Tabs-link" href="#sellers">
                    <span>{% trans "Продавцы" %}</span>
                </a>
                <a class="Tabs-link" href="#addit">
                    <span>{% trans "Характеристики" %}</span>
                </a>
                <a class="Tabs-link" href="#reviews">
                    <span>{% trans "Отзывы" %} {{ num_review }}</span>
                </a>
            </div>
            <div class="Tabs-wrap">
              <div class="Tabs-block" id="description">
                <p>
                  {{ product.description }}
                </p>

              </div>
              <div class="Tabs-block" id="sellers">
                <div class="Categories Categories_product">
                  {% for product in sellers_price %}
                  <div class="Categories-row">
                    <div class="Categories-block Categories-block_info">
                      <div class="Categories-info">
                        <strong>
                            <a class="btn btn_primary" href="{% url 'seller' product.seller_id %}">
                                {{ product.seller }}
                            </a>
                        </strong>
                      </div>
                    </div>
                    <div class="Categories-splitProps">
                    </div>
                    <div class="Categories-block Categories-price">
                      {% if product.sale %}
                        <strong><s>₽&#32;{{ product.price_old }}</s></strong>
                        <p><strong>₽&#32;{{ product.price }}0</strong></p>
                      {% else %}
                        <strong>₽&#32;{{ product.price }}
                        </strong>
                      {% endif %}
                    </div>
{#                    <div class="Categories-block Amount Amount_product">#}
{#                      <button class="Amount-remove" type="button">#}
{#                      </button>#}
{#                      <input class="Amount-input form-input" name="amount" type="text" value="1"/>#}
{#                      <button class="Amount-add" type="button">#}
{#                      </button>#}
{#                    </div>#}
                    <div class="Categories-block Categories-button">
                        <a class="btn btn_primary" href="{% url 'add_cart' product_id=product_id product_price=product.price %}">
                            <img class="btn-icon" src="{% static "assets/img/icons/card/cart_white.svg" %}" alt="cart_white.svg"/>
                            <span class="btn-content">{% trans "Добавить в корзину" %}</span>
                        </a>
                    </div>
                  </div>
                  {% endfor %}
                </div>
              </div>
              <div class="Tabs-block" id="addit">
                <div class="Product-props">
                {% for group, characteristics in characteristics.items %}
                  <div class="Product-prop-title">
                    <strong>{{ group }}</strong>
                  </div>
                  {% for characteristic, value in characteristics %}
                    <div class="Product-prop">
                      <strong>
                        {{ characteristic }}
                      </strong>
                      <span>{{ value }}</span>
                    </div>
                  {% endfor %}
                {% endfor %}
                </div>
              </div>
              <div class="Tabs-block" id="reviews">
                <div class="Comments">
                  {% for review in reviews %}
                  <div class="Comment">
                    <div class="Comment-column Comment-column_pict">
                      <img class="Comment-avatar" src="{{ MEDIA_ROOT }}{{ review.customer.profile.avatar.url }}" alt='avatar'>
                    </div>
                    <div class="Comment-column">
                      <header class="Comment-header">
                        <div>
                          <strong class="Comment-title">{{ review.customer.profile.full_name }}
                          </strong><span class="Comment-date">
                          &#32;&#32;{{ review.date.day }}/&#32;&#32;{{ review.date.month }}/&#32;&#32;{{ review.date.year }}/
                          &#32;&#32;{{ review.date.hour }}:{{ review.date.minute }}
                          </span>
                        </div>
                      </header>
                      <div class="Comment-content">{{ review.description }}
                      </div>
                    </div>
                  </div>
                  {% endfor %}

                  <div class="Pagination">
                    <div class="Pagination-ins">
                      {% if reviews.has_previous %}
                      <a class="Pagination-element Pagination-element_prev" href="?page={{ reviews.previous_page_number }}#reviews">
                        <img style="margin: 0;" src="{% static "assets/img/icons/prevPagination.svg" %}" alt="prevPagination.svg"/>
                      </a>
                      {% endif %}
                      {% for page in reviews.paginator.page_range %}
                        {% if reviews.number == page %}
                        <a class="Pagination-element Pagination-element_current" href="?page={{ page }}#reviews">
                          <span class="Pagination-text">{{ page }}
                          </span>
                        </a>
                        {% elif page >= reviews.number|add:-2 and page <= reviews.number|add:2 %}
                        <a class="Pagination-element" href="?page={{ page }}#reviews">
                          <span class="Pagination-text">{{ page }}
                          </span>
                        </a>
                      {% endif %}
                      {% endfor %}
                      {% if reviews.has_next %}
                      <a class="Pagination-element Pagination-element_prev" href="?page={{ reviews.next_page_number }}#reviews">
                        <img style="margin: 0;" src="{% static "assets/img/icons/nextPagination.svg" %}" alt="nextPagination.svg"/>
                      </a>
                      {% endif %}
                    </div>
                  </div>

                  {% if request.user.is_authenticated and can_create_reviews %}
                  <header class="Section-header Section-header_product">
                    <h3 class="Section-title">{% trans "Написать отзыв" %}
                    </h3>
                  </header>
                  <div class="Tabs-addComment">
                    <form class="form" action="/product/{{ product.id }}/" method="post">
                      {% csrf_token %}
                      <div class="form-group">
                        <textarea class="form-textarea" name="description" maxlength="2000" required="" id="id_description" placeholder="{% trans "Ваш отзыв" %}"></textarea>
                      </div>

                      <div class="form-group">
                        <button class="btn btn_muted" type="submit">{% trans "Отправить отзыв" %}
                        </button>
                      </div>
                    </form>
                  </div>
                  {% elif request.user.is_authenticated and not can_create_reviews %}
                  <header class="Section-header Section-header_product">
                    <h3 class="Section-title">{% trans "Вы уже оставляли отзыв на данный товар" %}
                    </h3>
                  </header>
                  {% else %}
                  <header class="Section-header Section-header_product">
                    <h3 class="Section-title">{% trans "Чтобы оставить отзыв, вам нужно" %}
                      <a href="{% url 'login' %}">{% trans "авторизоваться" %}</a>
                    </h3>
                  </header>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock %}

market/templates/registration.html
{% extends "base/base.html" %}
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% trans "Регистрация" %}</title>
</head>
<body>
{% block content %}
    <div class="wrapper">
        <div class="header">
            <h3 class="sign-in">{% trans "Регистрация" %}</h3>

        </div>
        <div class="clear"></div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="{% trans "Зарегистрироваться" %}" />

            <div class="clear"></div>
        </form>
    </div>
{% endblock %}
</body>
</html>

market/templates/settings.html
{% extends "base/base.html" %}
{% load static %}

{% block body_header %}
{% endblock body_header %}

{% block content %}
    <h2>Настройки сайта</h2>
    <form method="post" action="">
        {% csrf_token %}
        {{ settings_forms.as_p }}
        <button type="submit">Сохранить</button>
    </form>
    <h3>Сброс кэша</h3>
    <form method="post" action="">
        {% csrf_token %}
        <p><button type="submit" name="section1">Сбросить кэш раздела 1</button></p>
        <p><button type="submit" name="section2">Сбросить кэш раздела 2</button></p>
        <p><button type="submit" name="section3">Сбросить кэш раздела 3</button></p>
        <p><button type="submit" name="all">Сбросить весь кэш</button></p>
    </form>


{% endblock content %}